### ISSUE TITLE
Minecraft message not sent to Telegram on Paper Minecraft

### ISSUE THREAD

**Issue by bentinata** [felixbade/minecraft-telegram-gateway#35]
Server: clean paper (build 162) without any modification or other plugin.
Tested with: OpenJRE 8 and OpenJRE 11

Telegram message get sent to Minecraft, but with warning.
```
[TelegramGateway] Plugin TelegramGateway v1.0 generated an exception while executing task 2
java.lang.NullPointerException: null
        at fi.felixbade.TelegramGateway.Main.lambda$onEnable$0(Main.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-162]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by felixbade** [comment]
The null pointer exception should now be fixed in 580d3dc.

**Comment by felixbade** [comment]
Similar issue #38 is now fixed, could you @bentinata verify if this problem still persists?

**Comment by felixbade** [comment]
Also related: #41

**Comment by felixbade** [comment]
Verified to work on Paper build 143.
